In [16]:
import re
string = '<p>Please click <a href="http://www.dr-chuck.com">here</a></p>'

In [17]:
re.findall('href="(.+)"',string)

['http://www.dr-chuck.com']

a = add cell above

b = add cell below

x = cut

c = copy

v = paste

m = markdown

y = code

dd(press double time d) = delete

esc = go to command mode(all above commands will work in command mode)

enter = go to edit mode(all below commands will work in edit mode)

ctrl + enter = execute and go to next cell

shift + enter = execute and remain on same cell
 

###Hello
> there you are

**bold**
*hehe*

$ a = b + c $

Aryaman<br>Pandey

- AARRYAA
- PPAANNDDEEYY<br>

***

1. >AARRYYAA
2. PPAANNDDEEYY


NumPy is slow, but pandas and matplotlib are built on it

In [3]:
x = {'hehehe':'heheheh', 'dkdjee':'kfksdf'}

In [1]:
import sys
import numpy as np
import pandas as pd

In [5]:
sys.getsizeof(x)

232

In [6]:
np.int8

numpy.int8

In [7]:
a = np.uint(1)

In [8]:
sys.getsizeof(a)

28

In [12]:
b = np.array([1,2,3,4,5,6])

In [13]:
np.array([b[0],b[1]])

array([1, 2])

In [14]:
b[1:3]

array([2, 3])

In [13]:
b[::2]

array([1, 3, 5])

In [14]:
b[[0,2,-1]]

array([1, 3, 6])

In [15]:
b[::-1]

array([6, 5, 4, 3, 2, 1])

In [16]:
c= np.array([2,5,8,22,5,66,45,78,0,5,47,0,8,70], dtype=float)

In [17]:
B = np.array([
	[
		[12,10,11],
		[3,2,1]
	],
	[
		[6,5,4],
		[3,2,1]
	]
])

In [18]:
B

array([[[12, 10, 11],
        [ 3,  2,  1]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [19]:
B.shape

(2, 2, 3)

In [20]:
B[1,0,1]

5

In [21]:
B.sum()

60

In [22]:
B.mean()

5.0

In [23]:
B.std()

3.763863263545405

In [24]:
B.sum(axis=1)

array([[15, 12, 12],
       [ 9,  7,  5]])

In [25]:
B.mean(axis=0)

array([[9. , 7.5, 7.5],
       [3. , 2. , 1. ]])

In [26]:
B.std(axis=2)

array([[0.81649658, 0.81649658],
       [0.81649658, 0.81649658]])

In [21]:
C = np.array([
	[
		[12,10,11],
		[3,2,1]
	],
	[
		[6,5,4]
	]
],dtype=object)
#see what happens when you dont write dtype=object

In [22]:
C.shape

(2,)

In [29]:
X = np.array([
	[1,2,3,4],
	[5,6,7,8],
	[9,10,11,12],
	[13,14,15,16]
])

In [30]:
X[1] = np.array([99,99,99,99])

In [31]:
X

array([[ 1,  2,  3,  4],
       [99, 99, 99, 99],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [32]:
X[1] = np.array([12,55,70,1])

In [33]:
X

array([[ 1,  2,  3,  4],
       [12, 55, 70,  1],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [35]:
X+10

array([[11, 12, 13, 14],
       [22, 65, 80, 11],
       [19, 20, 21, 22],
       [23, 24, 25, 26]])

In [36]:
X*10

array([[ 10,  20,  30,  40],
       [120, 550, 700,  10],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])

In [62]:
ax = np.arange(5)

In [63]:
ax

array([0, 1, 2, 3, 4])

In [64]:
ax*10

array([ 0, 10, 20, 30, 40])

In [65]:
ax[[True,True,False,False,True]]

array([0, 1, 4])

In [66]:
ax[ax<=3]

array([0, 1, 2, 3])

In [68]:
ax[ax>ax.mean()]

array([3, 4])

In [69]:
ax[~(ax>ax.mean())]

array([0, 1, 2])

In [70]:
ax[(ax<=2) & (ax%2==0)]

array([0, 2])

In [23]:
A= np.array([
	[1,2,3],
	[4,5,6],
	[7,8,9]
])
B= np.array([
	[6,5],
	[4,3],
	[2,1]
]) 

In [24]:
A.dot(B)    #dot product

array([[20, 14],
       [56, 41],
       [92, 68]])

In [73]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [25]:
B.T   #transpose

array([[6, 4, 2],
       [5, 3, 1]])

In [76]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

In [26]:
G7_population = pd.Series([35.467, 63.951, 80.940, 60.665, 127.061, 64.511, 318.523])

In [27]:
G7_population.name = 'Population of G7 nations'

In [28]:
G7_population

0     35.467
1     63.951
2     80.940
3     60.665
4    127.061
5     64.511
6    318.523
Name: Population of G7 nations, dtype: float64

In [29]:
G7_population.dtype

dtype('float64')

In [30]:
G7_population.values

array([ 35.467,  63.951,  80.94 ,  60.665, 127.061,  64.511, 318.523])

In [31]:
type(G7_population.values)

numpy.ndarray

In [32]:
G7_population[1]

63.951

In [33]:
G7_population.index = [
   'Canada',
   'France',
   'Germany',
   'Italy',
   'Japan',
   'United Kingdom',
   'United States',
]

In [36]:
G7_population

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population of G7 nations, dtype: float64

In [22]:
G7_population['Canada']

35.467

In [24]:
G7_population[['Italy','France']]

Italy     60.665
France    63.951
Name: Population of G7 nations, dtype: float64

In [37]:
G7_population.iloc[-1]

318.523

In [45]:
G7_population['Canada':'Italy']

Canada     35.467
France     63.951
Germany    80.940
Italy      60.665
Name: Population of G7 nations, dtype: float64

In [46]:
G7_population>70

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: Population of G7 nations, dtype: bool

In [47]:
G7_population[G7_population>70]

Germany           80.940
Japan            127.061
United States    318.523
Name: Population of G7 nations, dtype: float64

In [49]:
G7_population[G7_population>G7_population.mean()]

Japan            127.061
United States    318.523
Name: Population of G7 nations, dtype: float64

In [50]:
G7_population.sum()

751.118

In [51]:
G7_population.std()

97.24996987121581

In [53]:
G7_population['France':'Italy'].mean()

68.51866666666666

In [55]:
G7_population.mean()

107.30257142857144

In [56]:
G7_population[(G7_population>80) & (G7_population<200)]

Germany     80.940
Japan      127.061
Name: Population of G7 nations, dtype: float64

In [62]:
G7_population

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population of G7 nations, dtype: float64

In [61]:
G7_population[0] = 35.467

In [2]:
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    'GDP': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
}, columns=['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'])

In [3]:
df

Population       GDP  Surface Area    HDI Continent
0      35.467   1785387       9984670  0.913   America
1      63.951   2833687        640679  0.888    Europe
2      80.940   3874437        357114  0.916    Europe
3      60.665   2167744        301336  0.873    Europe
4     127.061   4602367        377930  0.891      Asia
5      64.511   2950039        242495  0.907    Europe
6     318.523  17348075       9525067  0.915   America

In [4]:
df.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
]

In [5]:
df

Population       GDP  Surface Area    HDI Continent
Canada              35.467   1785387       9984670  0.913   America
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [6]:
df.columns

Index(['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'], dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, Canada to United States
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Population    7 non-null      float64
 1   GDP           7 non-null      int64  
 2   Surface Area  7 non-null      int64  
 3   HDI           7 non-null      float64
 4   Continent     7 non-null      object 
dtypes: float64(2), int64(2), object(1)
memory usage: 336.0+ bytes


In [10]:
df.size

35

In [11]:
df.shape

(7, 5)

In [12]:
df.describe()

Population           GDP  Surface Area       HDI
count    7.000000  7.000000e+00  7.000000e+00  7.000000
mean   107.302571  5.080248e+06  3.061327e+06  0.900429
std     97.249970  5.494020e+06  4.576187e+06  0.016592
min     35.467000  1.785387e+06  2.424950e+05  0.873000
25%     62.308000  2.500716e+06  3.292250e+05  0.889500
50%     64.511000  2.950039e+06  3.779300e+05  0.907000
75%    104.000500  4.238402e+06  5.082873e+06  0.914000
max    318.523000  1.734808e+07  9.984670e+06  0.916000

In [15]:
df.dtypes.value_counts()

int64      2
float64    2
object     1
dtype: int64

In [16]:
df.loc['Canada']

Population       35.467
GDP             1785387
Surface Area    9984670
HDI               0.913
Continent       America
Name: Canada, dtype: object

In [17]:
df.iloc[-1]

Population       318.523
GDP             17348075
Surface Area     9525067
HDI                0.915
Continent        America
Name: United States, dtype: object

In [20]:
df['Population']

Canada             35.467
France             63.951
Germany            80.940
Italy              60.665
Japan             127.061
United Kingdom     64.511
United States     318.523
Name: Population, dtype: float64

In [23]:
df.loc['France':'Italy']

Population      GDP  Surface Area    HDI Continent
France       63.951  2833687        640679  0.888    Europe
Germany      80.940  3874437        357114  0.916    Europe
Italy        60.665  2167744        301336  0.873    Europe

In [24]:
df.loc['France':'Italy','Population']

France     63.951
Germany    80.940
Italy      60.665
Name: Population, dtype: float64

In [27]:
df.loc['France':'Italy',['Population','GDP']]

Population      GDP
France       63.951  2833687
Germany      80.940  3874437
Italy        60.665  2167744

In [29]:
df.iloc[[0,1,-1]]

Population       GDP  Surface Area    HDI Continent
Canada             35.467   1785387       9984670  0.913   America
France             63.951   2833687        640679  0.888    Europe
United States     318.523  17348075       9525067  0.915   America

In [35]:
df.loc[df['Population'] > 70]

Population       GDP  Surface Area    HDI Continent
Germany            80.940   3874437        357114  0.916    Europe
Japan             127.061   4602367        377930  0.891      Asia
United States     318.523  17348075       9525067  0.915   America

In [38]:
df.loc[df['Population'] > 70, ['Population','GDP']]

Population       GDP
Germany            80.940   3874437
Japan             127.061   4602367
United States     318.523  17348075

In [7]:
df.drop('Canada')

Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [8]:
df[['Population','GDP']] /100

Population        GDP
Canada             0.35467   17853.87
France             0.63951   28336.87
Germany            0.80940   38744.37
Italy              0.60665   21677.44
Japan              1.27061   46023.67
United Kingdom     0.64511   29500.39
United States      3.18523  173480.75

Posters required

March*
8th March- International women’s Day
18th March- Holi
April
April 30-Anti-Child Labour Day
May
1st May: International Labour Day or May Day
10 May - Mother's Day (Second Sunday of May)
24 May:Eid al-Fitr
June
5th june-Environment day
21 june -Yoga day

Everyone in the group please pick up any days poster by 6:00 pm 
And submit it 48 hrs before the festival.